[package]
name = "j-polars"
version = "0.1.0"
edition = "2021"

[workspace]

[features]
header = []
footer = []

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
jni="0.20.0"
polars="*"